spring:
  config:
    import: classpath:project.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=organizer
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    locations: "classpath:db.migrations"
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    defaultSchema: organizer